### ISSUE TITLE
add PT-BR (Brasilian Portuguese) language mental health links

### ISSUE THREAD

**Issue by andy5995** [mhwkb/mhwkb#100]
make an PT-BR directory under [Knowledge Base](https://github.com/andy5995/mhwkb/tree/master/Knowledge_Base/) and add some links.

Ex. Sites or articles that begin with "w"  should go into PT-BR/w.md

the file format

```
[When meditation seems to stir up negative emotion](https://www.wildmind.org/metta/metta-four/stirred-up-emotion)<br />
2007-12-04<br />
"tags": ["meditation", "negativity", "Buddhism"]<br />
-<br />
[World needs “revolution” in mental health care – UN rights expert](http://www.ohchr.org/EN/NewsEvents/Pages/DisplayNews.aspx?NewsID=21689&LangID=E)<br />
2014-09-13<br />
"tags": ["doctors", "press releases", "human rights", "UN"]<br />
-<br />

```

Please remember to **"star"** this project (upper right corner) and feel free to [join the project chat room](https://join.slack.com/t/mhwkb/shared_invite/enQtMjU3MjcwMTk4NjYzLTA0ZDc2YjAwMDJiNTU1YTBmYTViNmQ5MTdjOTk2MDA2MDMyMzNiYjU4ZWIzMTZlNmU4ZjFhNDg1MjQ5OGQyMjI).

See [CONTRIBUTING.md](https://github.com/andy5995/mhwkb/blob/master/CONTRIBUTING.md) for important information about first-time contributions and proper PR procedure.

**Comment by localhostpedro** [comment]
@andy5995 can you assign me ?

**Comment by andy5995** [comment]
This repo is deprecated, but the info for the new one is at https://github.com/mhwkb/mhwkb.github.io/issues/11

**Comment by andy5995** [comment]
@localhostpedro I added a ticket on the other repo for this: https://github.com/mhwkb/mhwkb.github.io/issues/113

I'm sorry for the confusion.
