### ISSUE TITLE
search box for web site

### ISSUE THREAD

**Issue by andy5995** [mhwkb/mhwkb#105]
@jamielthompson29 wrote in #89 
>I noticed I can click on a tag & it will search, but what about a searching option at the top maybe? Sorry if this is already in the issues list & I just haven't seen it.

Oh, no worries. No one has asked about it yet, but I realized that it would be an issue that came up. So.. good question!

Right now, the site is on GitHub's servers, and I'm not sure yet how I'd implement a search feature such as you suggested (I've done it on other servers, I just don't have much xp with GitHub servers). We started discussing changing the software used to build the site, where it should be hosted, and a few other things, such as how to make the site more user-friendly.

**Comment by erichoog** [comment]
One thing I had thought of is that if we had the links stored in JSON format or in a DB for the back-end  (#87) we could use a front-end framework or something like AngularJS and use the filtering features of that.  That would take some pretty big changes with everything as it is now but it's just a thought.

**Comment by erichoog** [comment]
I'm not 100% sure this would make sense but if the C program could produce a .json file or embed a collection in the header or something then you could use that to provide data to AngularJS and its all client side so i would think it would work on the GitHub pages.

**Comment by andy5995** [comment]
@erichoog Thanks for your voice. :) I think we'll hold off on this for now. I replied in more detail in https://github.com/andy5995/mhwkb/issues/106#issuecomment-338526816 which may set a record for the longest github comment EVER

**Comment by andy5995** [comment]
moved to mhwkb/mhwkb.github.io#63
