### ISSUE TITLE
dates can be removed

### ISSUE THREAD

**Issue by andy5995** [mhwkb/mhwkb#109]
https://github.com/andy5995/mhwkb/blob/5a129e51b0e76e3e12cf60baa0b4705e127d93ba/src/main.c#L157

This will require minor changes to the source code and the templates.

They don't have to removed from the entries in the KB all at once. That can be worked on by multiple people over time.

**Comment by jamielthompson29** [comment]
I would like to try to hit this later tonight :) If someone hits it before me thats fine :)

**Comment by jamielthompson29** [comment]
I have removed it from the template successfully & pushed it up on a branch of my fork. Working on removing it from other files, but getting some complaints when I run "make".  I will have to pick back up on this tomorrow or the next day though. Let me know if you need me to make a PR for what I have so far :)

**Comment by andy5995** [comment]
Thanks @jamielthompson29 

Normally it's best to make a separate branch for separate issues.

Sounds like you're having trouble with `make` after editing some of source code, so yes, you can push your changes if you're stuck and I'd be glad to take a look.

>I will have to pick back up on this tomorrow or the next day though

Ok, we'll touch base when it's convenient. :)
