### ISSUE TITLE
enlarge tags and increase font

### ISSUE THREAD

**Issue by andy5995** [mhwkb/mhwkb#126]
If I recall correctly, @parthsuresh noted that the tags needed to be bigger.

They're not too bad on the desktop but on mobile devices.

We use the [Bootstrap](https://github.com/mhwkb/mhwkb/blob/master/CONTRIBUTING.md#css-design-we-use-bootstrap) toolkit for CSS.

**Comment by nealkarpe** [comment]
Hi! Can I be assigned to this?

**Comment by andy5995** [comment]
Hi @nealkarpe Thanks for your interest.

Yes, you can be. But we'll likely be switching to another site. I'm not sure exactly when yet. If you'd still like to work on this, please do. :)

**Comment by nealkarpe** [comment]
Ok, I'll work on this. :smiley:

**Comment by andy5995** [comment]
This can be done on the new Jekyll site when it's ready. (#132)

Are you still interested in doing this @nealkarpe ? I can ping you when the time comes. I hope you weren't inconvenienced.

**Comment by nealkarpe** [comment]
Hi really sorry for the delay. I was preoccupied with some other work. I'll finish this now asap! Please assign this similar issue to me in the new repo. Cheers! :smile:

**Comment by nealkarpe** [comment]
The other repo seems ready? Should I go ahead and make a PR or is there something still pending?

**Comment by andy5995** [comment]
Hi @nealkarpe thanks for following up. No problem about the delay. It kind of worked out well. :)

We are working on the new site on a different branch in this repo. When it's ready, it will be deployed (probably within the next 3 or 4 days) to the master branch of the other repo. That will be the best time to do the PR, and will ensure that GitHub will record your contribution properly.

**Comment by andy5995** [comment]
@nealkarpe I believe we are all ready for you.

The information you need is here, but we haven't refined the docs yet. So if you have any questions, let us know.

https://github.com/mhwkb/mhwkb.github.io/wiki/Testing
