### ISSUE TITLE
Implementing Jekyll

### ISSUE THREAD

**Issue by andy5995** [mhwkb/mhwkb#127]
I'm not completely familiar with @jekyll yet, but from what I can tell so far, it seems like a very suitable option.

If there's no objections, let's switch to it.

Can @parthsuresh handle the initial set-up?

**Comment by andy5995** [comment]
@erichoog said he would be interested in the initial set up if @parthsuresh was unavailable.

@SunyataZero (Tord) said he has some experience and offered his help if we needed it.

At the start, we'll make the changes on the gh-pages branch here. The site will show up at https://mhwkb.github.io/mhwkb/

After everything is set up, we'll copy everything over to the repo at https://github.com/mhwkb/mhwkb.github.io, which will result in https://mhwkb.github.io/ showing the new jekyll site.

**Comment by andy5995** [comment]
I'm thinking a blog-type format would be best, so it'll be a little different from up-for-grabs

With up for grabs, clicking a link will direct the user to the external site.

What's needed is a separate page for each link, so disqus can be used.

So visualize.. "Wordpress" style, but the body of each "post" will only contain the link to the external site. The "post" will have tags (edited)

But the main pages will have lists of posts, just like Wordpress. 10 posts per page is what I'm thinking

Since I know little about Jekyll, I'm not sure how we'll be able to handle the separate Language pages yet. I'd like something like there is now... https://mhwkb.github.io/ (links at the top, the language pages are separated)

**Comment by erichoog** [comment]
This might take me a while to learn.  I've been able to get a basic Jekyll site running on my local machine but still learning how to work with the template engine etc.

In looking for information on how to add tags to be displayed in the post pages I came across an example where someone has added discus, so this page / repo might be helpful for reference:

https://github.com/codinfox/codinfox-lanyon/blob/dev/_layouts/post.html

**Comment by andy5995** [comment]
>This might take me a while to learn.

I'll spend some time today trying to learn more about jekyll. Maybe I can push a bare bones set-up to the repo and we can go from there.

**Comment by erichoog** [comment]
That sounds good to me!  I don't think creating the post files will be too difficult but.more so just learning the template engine. I'm hoping to have some time to work on more later as well!


-------- Original message --------

**Comment by andy5995** [comment]
>I don't think creating the post files will be too difficult

http://import.jekyllrb.com/docs/wordpressdotcom/

I had a wordpress xml file that contained posts, categories, and pages. I successfully ran the importer so have some pretty good examples!

**Comment by andy5995** [comment]
This is completed, and the new repo is at https://github.com/mhwkb/mhwkb.github.io
