### ISSUE TITLE
links to be added

### ISSUE THREAD

**Issue by andy5995** [mhwkb/mhwkb#27]
If you don't have time to do a PR, you can add links to this ticket.

If you do have time to do a PR, please add some of these links to the KB. :)

Please remember to "star" this project (upper right corner).

 See [CONTRIBUTING.md](https://github.com/andy5995/mhwkb/blob/master/CONTRIBUTING.md) for important information about **tagging guidelines** and **categorization**

To Add:

https://mensmovement.com/

http://bringchange2mind.org/

http://www.slowmovement.com/

http://recd.co.nz/ @Herbyvoire

**Comment by sonro** [comment]
Hi there I would like to add the links listed here to the KB

**Comment by andy5995** [comment]
Hi @sonro 

Thanks for the offer. We are going to be reformatting the data files soon, but after that, you're welcome to add some links. I'll follow up with you here when the time comes. You're welcome to join the chat room, too.

**Comment by sonro** [comment]
Excellent, I'll stay subscribed to this issue. I am also happy to help move over the existing links to the new format once it has been established.

**Comment by andy5995** [comment]
Hi @sonro 

The format of the posts now:

filename must be preceded by the date, in this format:
(Use the date you create the post file)
2017-10-28-side_effects_book_alison_bass.md

```
---
layout: post
title: "Side Effects: A Prosecutor, a Whistleblower, and a Bestselling Antidepressant on Trial"
date:   2017-10-28 12:00:00 -0500
tags:
- books
- Alison Bass
- journalism
- side effects
- conflicts-of-interest
categories: EN
href: http://a.co/0BuSDiT
---
```

You'll be doing your PR at this repo, adding files to this directory:

https://github.com/mhwkb/mhwkb.github.io/tree/master/_posts

The posts will be live on our new site, once it's deployed in a few days, but you can start adding some any time you'd like.

Please only do up to 3 though, then submit a PR.

**Comment by andy5995** [comment]
To make this easier, you can now  use the jekyll post generator that @luiemilio created:

https://github.com/luiemilio/jekyll_post_generator

**Comment by andy5995** [comment]
@sonro , Feel free to do as many as you like, but don't get burnt out! :) Thanks a lot for your recent submissions!

**Comment by mbabatunde** [comment]
Hi, I'd like to help out with this issue too! How can I get started?

**Comment by andy5995** [comment]
Hi @mbabatunde . Thanks for the offer. The project page has moved ot 

https://github.com/mhwkb/mhwkb.github.io

These tickets show a couple links that can be added:

https://github.com/mhwkb/mhwkb.github.io/issues?q=is%3Aissue+is%3Aopen+label%3A%22link+suggestion%22

Other details are in this ticket:
https://github.com/mhwkb/mhwkb.github.io/issues/11

Please let me know if you have any other questions. :)

**Comment by andy5995** [comment]
I'll add the 4 remaining links at the top to the new site within the next week.
