### ISSUE TITLE
add pagination to web site

### ISSUE THREAD

**Issue by andy5995** [mhwkb/mhwkb#38]
This has to wait until #37 and #36  are resolved

Web site will need pagination on the index and tag pages.

So imagine a navigation bar added near the top, linking to each page:

For example, if there are 73 links on index.html (20 links per page):
`<Next 1 2 3 4 Last>`

If there are 33 links on a `<tag>.html` page:
`<Next 1 2  Last>`

I expect it will require some discussion on how to implement it. Unless some expert comes along and figures it out by himself.

Here's the web site: https://mhwkb.github.io/

I don't know when we'll be able to start on this, but if you're interested, leave a note here or subscribe to the ticket.

**Comment by andy5995** [comment]
Here's one method I thought of:

Do a "dry-run" first, getting the count for each tag.

So.. no html files would be written, only the tag names would be counted.

If 23 links were tagged with "books", that number would be stored in books.txt. 

After the "dry-run", we'd know how how many pages would be needed for each "books" page (after some simple math), so could output a pagination nav bar when the html footer is added.

I'm thinking 20 links per page. One column. It seems that if there were 2 columns with 20 links... that would just be a  lot of links on one page and harder for a reader to sift through. Thoughts on this?

**Comment by parthsuresh** [comment]
This approach seems fine @andy5995 . Shall I start working on it?

**Comment by andy5995** [comment]
That'd be great if you take this ticket! But we have to wait for #37 to be completed. Thanks!

@parthsuresh I invited you to be a collaborator, once you accept that I can assign this ticket to you.

**Comment by andy5995** [comment]
@dafky2000 wrote in #37 
>Don't worry about (not) working on files at the same time, this one may take a minute. I'll keep up to date and resolve merge conflicts as I go!

@parthsuresh It should be ok now to set up that 2D array, but I don't think there would be much point in making the links until Dan's template is in place.

**Comment by andy5995** [comment]
@parthsuresh I got your messages in Slack. Sounds like you completed part of this :) And PR #51 has been merged so you should be able to add nav links easily now.

**Comment by andy5995** [comment]
afaik, @parthsuresh  hasn't started on this yet.

This would be done a different way after jekyll is implemented (#127)

https://jekyllrb.com/docs/pagination/
