### ISSUE TITLE
Visible page heading title design

### ISSUE THREAD

**Issue by andy5995** [mhwkb/mhwkb#91]
Ideas on what to use for the visible page heading on the `<tag>`.html pages? And any background decoration/color?

https://mhwkb.github.io/veterans.html

Some options would be:

# Mental Health and Wellness Knowledge Base
## veterans ##

or

# veterans #
## Mental Health and Wellness Knowledge Base

or

## veterans | Mental Health and Wellness Knowledge Base

or leave as is.

**Comment by jamielthompson29** [comment]
Hi, would you be interested in a maybe a graphic or something? I might be able to put something together, post it here for review, add it then make a pull request? :)

**Comment by andy5995** [comment]
Yes, that would be great! We have no graphic designers on our team yet!

I'm not very good at design, so I haven't tried to visualize anything. I was hoping for people who would be interested in presenting their own ideas!

The color theme of the site hasn't been written in stone yet (We just recently got a basic design with CSS in place). So I would say it's not necessary to try to match our current theme.

**Comment by jamielthompson29** [comment]
Ok cool I'll mess around & see what I can come up with :)
